<img src="https://i2.wp.com/hackwagon.com/wp-content/uploads/2017/02/Logo-Web-Export.png?ssl=1" width=200/>

<h1>Hackwagon Academy DS102 - Problem Set 1</h1>
<hr>

This Problem Set consists of 20 questions, with each correct answer to be awarded 1 mark, totalling up to 20 marks.

If you have any questions to the Problem Set, feel free to send a message to your TAs or Instructors in the Telegram chat. You are encouraged to also discuss the problem sets within your own groups. 

Before you seek help, please consider looking at onlines resources such as documentations and try out those solutions first. This will greatly enhance your learning experience. Being stuck is part of the learning experience so don't worry!

<b>Attempt but minor syntax errors are awarded half the mark.</b>

In [1]:
#Before you start, please perform the following 2 steps:
#1. Rename the file to FirstName_LastName Hackwagon Academy DS102 - Problem Set 1 
#   e.g. John_Doe Hackwagon Academy DS102 - Problem Set 1

#2. Fill in your details here:
#Name                    : _________Lim Yu Guang______________

#Start of Course Class(Edit accordingly): __24 May 2020____

# FOR TA/INSTRUCTOR 
# Total Marks:  19.5 / 20

#### Credits 

This problem set is inspired by the [Lending Club Loan Data](https://www.kaggle.com/wendykan/lending-club-loan-data).

<img src="https://d1ic4altzx8ueg.cloudfront.net/niche-builder/5cb94cef96518.png" width=300>

## Context 

Congratulations! You've just joined LendingClub as their Data Analyst. LendingClub is a US peer-to-peer lending company, headquartered in San Francisco, California. It was the first peer-to-peer lender to register its offerings as securities with the Securities and Exchange Commission (SEC), and to offer loan trading on a secondary market. 

Your project manager, Silver, knows you had just taken an intensive course on Data Analytics with Python has tasked your first Data Science project.  The project given to you is to help LendingClub prepare a prediction model to help them detect loan defaulters. As with all Data Science projects, Data Preprocessing is a crucial stage in any Data Science project, as such, this will be your very first task. 

The dataset handed to you are loans issued through 2007 - 2015 period including loan status. A data dictionary (`LCDataDictionary`) is also provided for you to get a better understanding of the dataset. 

Note: This problem set only tackles the <b>Data Gathering and Preprocessing</b> stage of the Data Science project.

## Data Wrangling & Preprocessing - 15 marks

### Q1. Open Files and Combine Datasets

You're given two datasets:

1. `loans-10k-1.csv`
2. `loans-10k-2.csv`

Combine these two datasets into a single dataframe as `df_all`.

In [55]:
import pandas as pd
df_1 = pd.read_csv("loans-10k-1.csv")
df_2 = pd.read_csv("loans-10k-2.csv")

df_all = pd.concat([df_1, df_2])

df_all.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,1800,1800,1800.0,36 months,19.52,66.46,E,E2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,6800,6800,6800.0,36 months,7.97,213.00,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,18000,18000,18000.0,36 months,12.49,602.08,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,17375,17375,17375.0,36 months,13.11,586.36,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,14000,14000,14000.0,60 months,13.59,322.79,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED:1/1

### Q2. Inspect DataFrame

Inspect the new DataFrame and know how many columns/variables you're working with.

In [4]:
df_all.shape
# How many rows and variables/columns are there in this dataset
# rows = 20000
# columns = 145

(20000, 145)

In [5]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

# Handling Missing Data

Upon inspection, you noticed there are several missing values, like `NaN`, Not A Number, within the dataset. This pattern repeats for several columns. You have decided to inspect these columns further by investigating each column for the number of rows with missing values. You decide that you will drop columns where the number of rows with missing values are above a certain threshold, for this case would be 90%.  

### Q3. Find Missing Data Per Column

Using `.isnull()`, get the number of rows with missing data for each column using `.sum()` and store this Series as `missing_counts`. 

**Expected Output**:

    id                 20000
    member_id          20000
    loan_amnt              0
    funded_amnt            0
    funded_amnt_inv        0
    dtype: int64

In [6]:
missing_counts = df_all.isnull().sum()
missing_counts

id                                            20000
member_id                                     20000
loan_amnt                                         0
funded_amnt                                       0
funded_amnt_inv                                   0
term                                              0
int_rate                                          0
installment                                       0
grade                                             0
sub_grade                                         0
emp_title                                      1427
emp_length                                     1261
home_ownership                                    0
annual_inc                                        0
verification_status                               0
issue_d                                           0
loan_status                                       0
pymnt_plan                                        0
url                                           20000
desc                                          18825
purpose                                           0
title                                           234
zip_code                                          0
addr_state                                        0
dti                                              13
delinq_2yrs                                       2
earliest_cr_line                                  2
inq_last_6mths                                    2
mths_since_last_delinq                        10167
mths_since_last_record                        16925
                                              ...
sec_app_open_acc                              19079
sec_app_revol_util                            19090
sec_app_open_act_il                           19079
sec_app_num_rev_accts                         19079
sec_app_chargeoff_within_12_mths              19079
sec_app_collections_12_mths_ex_med            19079
sec_app_mths_since_last_major_derog           19693
hardship_flag                                     0
hardship_type                                 19909
hardship_reason                               19909
hardship_status                               19909
deferral_term                                 19909
hardship_amount                               19909
hardship_start_date                           19909
hardship_end_date                             19909
payment_plan_start_date                       19909
hardship_length                               19909
hardship_dpd                                  19909
hardship_loan_status                          19909
orig_projected_additional_accrued_interest    19934
hardship_payoff_balance_amount                19909
hardship_last_payment_amount                  19909
disbursement_method                               0
debt_settlement_flag                              0
debt_settlement_flag_date                     19678
settlement_status                             19678
settlement_date                               19678
settlement_amount                             19678
settlement_percentage                         19678
settlement_term                               19678
Length: 145, dtype: int64

In [7]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q4. Get Missing Rows Information For Each Column

Create a new Series called `missing_percentage` where it is the `missing_counts` divided by the number of rows, `len(df)`. With the two Series created, create a new DataFrame called, `missing_info_df`. 

After creating this new DataFrame, <b>filter</b> only for rows with at least 1 missing value and <b>display it</b>. 

**Expected Output**:

<img src="https://i.imgur.com/gDQkDey.png">

In [8]:
percent_counts = missing_counts / len(df_all) * 100
missing_info_df = pd.DataFrame({'Count' : missing_counts, 'Percent' : percent_counts})
cond1 = missing_info_df['Count'] >= 1

missing_info_df[cond1]

                                            Count  Percent
id                                          20000  100.000
member_id                                   20000  100.000
emp_title                                    1427    7.135
emp_length                                   1261    6.305
url                                         20000  100.000
desc                                        18825   94.125
title                                         234    1.170
dti                                            13    0.065
delinq_2yrs                                     2    0.010
earliest_cr_line                                2    0.010
inq_last_6mths                                  2    0.010
mths_since_last_delinq                      10167   50.835
mths_since_last_record                      16925   84.625
open_acc                                        2    0.010
pub_rec                                         2    0.010
revol_util                                     23    0.115
total_acc                                       2    0.010
last_pymnt_d                                   19    0.095
next_pymnt_d                                11714   58.570
collections_12_mths_ex_med                      3    0.015
mths_since_last_major_derog                 14807   74.035
annual_inc_joint                            18976   94.880
dti_joint                                   18976   94.880
verification_status_joint                   19012   95.060
acc_now_delinq                                  2    0.010
tot_coll_amt                                  675    3.375
tot_cur_bal                                   675    3.375
open_acc_6m                                  7777   38.885
open_act_il                                  7777   38.885
open_il_12m                                  7777   38.885
...                                           ...      ...
sec_app_earliest_cr_line                    19079   95.395
sec_app_inq_last_6mths                      19079   95.395
sec_app_mort_acc                            19079   95.395
sec_app_open_acc                            19079   95.395
sec_app_revol_util                          19090   95.450
sec_app_open_act_il                         19079   95.395
sec_app_num_rev_accts                       19079   95.395
sec_app_chargeoff_within_12_mths            19079   95.395
sec_app_collections_12_mths_ex_med          19079   95.395
sec_app_mths_since_last_major_derog         19693   98.465
hardship_type                               19909   99.545
hardship_reason                             19909   99.545
hardship_status                             19909   99.545
deferral_term                               19909   99.545
hardship_amount                             19909   99.545
hardship_start_date                         19909   99.545
hardship_end_date                           19909   99.545
payment_plan_start_date                     19909   99.545
hardship_length                             19909   99.545
hardship_dpd                                19909   99.545
hardship_loan_status                        19909   99.545
orig_projected_additional_accrued_interest  19934   99.670
hardship_payoff_balance_amount              19909   99.545
hardship_last_payment_amount                19909   99.545
debt_settlement_flag_date                   19678   98.390
settlement_status                           19678   98.390
settlement_date                             19678   98.390
settlement_amount                           19678   98.390
settlement_percentage                       19678   98.390
settlement_term                             19678   98.390

[110 rows x 2 columns]

In [9]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/ 1

### Q5. Drop Insignificant Columns

You've decided that there are many columns that have more than 90% missing values. You decide to drop these columns with the `.dropna` method, set to a threshold to 90% of the <b>total number of rows</b>. Set the new filtered DataFrame as `loans_significant_df`. 

<i>Hint: Check the <code>thresh</code> argument and set it <b>integer</b> value</i>

**Expected Output**:

<img src="https://i.imgur.com/T1mNDfG.png">

In [10]:
thresh_hold = int(0.9 * len(df_all))
loans_significant_df = df_all.dropna(thresh = thresh_hold, axis = 1)
loans_significant_df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,1800,1800,1800.0,36 months,19.52,66.46,E,E2,SALES,< 1 year,...,0.0,0.0,0.0,493603.0,75657.0,3000.0,87296.0,N,Cash,N
1,6800,6800,6800.0,36 months,7.97,213.00,A,A5,Project Manager,5 years,...,50.0,0.0,0.0,391852.0,39987.0,11300.0,62152.0,N,Cash,N
2,18000,18000,18000.0,36 months,12.49,602.08,B,B4,Logistics coordinator,1 year,...,75.0,0.0,0.0,86907.0,82649.0,10700.0,74707.0,N,Cash,N
3,17375,17375,17375.0,36 months,13.11,586.36,B,B4,walmart,7 years,...,28.6,0.0,0.0,170959.0,25477.0,40900.0,0.0,N,Cash,N
4,14000,14000,14000.0,60 months,13.59,322.79,C,C2,supervisor,7 years,...,25.0,0.0,0.0,160592.0,28484.0,12700.0,20292.0,N,Cash,N
5,35000,35000,35000.0,60 months,12.73,791.53,B,B5,Project Manager,9 years,...,18.2,0.0,0.0,176527.0,107695.0,65100.0,64081.0,N,DirectPay,N
6,8000,8000,8000.0,36 months,12.74,268.56,C,C1,Customer Service,3 years,...,16.7,0.0,0.0,187445.0,16717.0,18500.0,8000.0,N,Cash,N
7,35000,35000,34975.0,60 months,17.57,880.61,D,D4,SALES MANAGER,10+ years,...,40.0,0.0,0.0,1094787.0,27137.0,25500.0,0.0,N,Cash,N
8,3000,3000,3000.0,36 months,11.49,98.92,B,B5,Bank Teller,10+ years,...,50.0,0.0,0.0,138902.0,31305.0,30800.0,25380.0,N,Cash,N
9,6000,6000,6000.0,36 months,14.03,205.16,C,C2,Plant Manager,4 years,...,0.0,0.0,0.0,140101.0,27804.0,6800.0,26700.0,N,Cash,N
10,3025,3025,3025.0,36 months,9.58,97.02,B,B1,Executive Assistant,10+ years,...,50.0,0.0,0.0,199915.0,35919.0,22100.0,20145.0,N,Cash,N
11,12875,12875,12875.0,36 months,13.67,437.98,B,B5,new york city transit,4 years,...,25.0,0.0,0.0,NaN,15412.0,11900.0,NaN,N,Cash,N
12,10800,10800,10800.0,60 months,18.55,277.50,E,E2,Account Manager,< 1 year,...,50.0,0.0,0.0,38212.0,31131.0,15200.0,20612.0,N,Cash,N
13,7000,7000,7000.0,36 months,7.89,219.00,A,A5,supervisor,5 years,...,25.0,0.0,0.0,27770.0,19004.0,9300.0,13070.0,N,Cash,N
14,10000,10000,10000.0,36 months,12.62,335.12,C,C1,Aircraft Maintainer,10+ years,...,66.7,0.0,0.0,291678.0,64700.0,6300.0,66806.0,N,Cash,N
15,30000,30000,30000.0,36 months,6.99,926.18,A,A2,"VP, Product Development",4 years,...,0.0,0.0,0.0,30200.0,1405.0,29000.0,0.0,N,Cash,N
16,24000,24000,24000.0,60 months,9.93,509.11,B,B2,V.P.,6 years,...,0.0,0.0,4.0,61665.0,46809.0,19200.0,42065.0,N,Cash,N
17,16000,16000,15950.0,60 months,14.33,375.04,C,C2,Amazon.com (Audible.com),8 years,...,71.4,0.0,0.0,325185.0,84389.0,13800.0,83953.0,N,Cash,N
18,16000,16000,16000.0,36 months,6.97,493.82,A,A3,Network Engineer,2 years,...,28.6,0.0,0.0,701636.0,82396.0,44300.0,80316.0,N,Cash,N
19,16000,16000,16000.0,60 months,14.46,376.12,C,C4,E-5,7 years,...,100.0,0.0,0.0,46995.0,38217.0,2800.0,32695.0,N,Cash,N
20,19200,19200,19200.0,60 months,8.18,390.97,B,B1,NaN,NaN,...,50.0,0.0,0.0,148231.0,74161.0,25900.0,56052.0,N,Cash,N
21,4000,4000,4000.0,36 months,12.12,133.09,B,B3,United States Army,3 years,...,50.0,0.0,0.0,13600.0,9662.0,5500.0,0.0,N,Cash,N
22,10000,10000,10000.0,36 months,10.90,326.92,B,B4,Warehouse Manager,10+ years,...,66.7,1.0,0.0,38982.0,13799.0,16500.0,21282.0,N,Cash,N
23,17350,17350,17350.0,36 months,10.99,567.94,B,B4,Teacher,10+ years,...,100.0,0.0,0.0,18700.0,17757.0,13800.0,0.0,N,Cash,N
24,1200,1200,1200.0,36 months,11.49,39.57,B,B5,Attorney,1 year,...,20.0,0.0,0.0,352756.0,168178.0,30200.0,134907.0,N,Cash,N
25,20000,20000,20000.0,60 months,9.75,422.49,B,B3,Finance Operations,1 year,...,0.0,0.0,0.0,302634.0,86373.0,25000.0,92684.0,N,Cash,N
26,12000,12000,12000.0,36 months,18.94,439.51,D,D2,Planner,8 years,...,100.0,1.0,0.0,50753.0,49972.0,11900.0,37053.0,N,Cash,N
27,30000,30000,30000.0,60 months,18.06,762.79,D,D2,Teacher,6 years,...,66.7,0.0,0.0,256772.0,84555.0,18300.0,89556.0,N,Cash,N
28,30000,30000,30000.0,60 months,20.20,798.16,D,D5,Compliance Analyst,6 years,...,66.7,0.0,0.0,179276.0,32876.0,12500.0,13404.0,N,Cash,N
29,3000,3000,3000.0,36 months,10.08,96.92,B,B1,Truck Driver,10+ years,...,0.0,0.0,0.0,313321.0,28466.0,18700.0,22915.0,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,12000,12000.0,36 months,12.62,402.14,C,C1,sales,10+ years,...,0.0,1.0,0.0,92437.0,55507.0,15200.0,67237.0,N,Cash,N
9971,8000,8000,8000.0,36 months,16.02,281.34,C,C5,warehouse superviser,10+ years,...,100.0,0.0,0.0,157220.0,7032.0,6200.0,2520.0,N,Cash,N
9972,10000,10000,10000.0,36 months,15.05,346.90,C,C4,Fabrication Technician,3 years,...,40.0,0.0,0.0,278319.0,64199.0,9700.0,60742.0,N,Cash,N
9973,20000,20000,20000.0,36 months,7.89,625.72,A,A5,Customer Care/ Planner,10+ years,...,60.0,0.0,0.0,238694.0,39777.0,23000.0,32901.0,N,Cash,N
9974,6000,6000,6000.0,36 months,14.49,206.50,C,C4,Account payable,< 1 year,...,100.0,0.0,0.0,106010.0,6881.0,2000.0,4500.0,N,Cash,N
9975,17500,17500,17500.0,60 months,16.99,434.83,D,D3,Catering Coordinator,3 years,...,75.0,0.0,0.0,17600.0,13924.0,15600.0,0.0,N,Cash,N
9976,18000,18000,18000.0,36 months,10.99,589.22,B,B3,Los Angeles County,5 years,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N
9977,10000,10000,10000.0,36 months,8.46,315.50,A,A5,Supervisor,3 years,...,0.0,0.0,0.0,52100.0,4471.0,49500.0,0.0,N,Cash,N
9978,22250,22250,22250.0,36 months,13.99,760.35,C,C4,Digital Service Advisor,< 1 year,...,100.0,0.0,0.0,85288.0,73250.0,25800.0,49688.0,N,Cash,N
9979,7000,7000,7000.0,36 months,15.02,242.73,C,C3,Consultant,1 year,...,14.3,0.0,0.0,93197.0,66065.0,53100.0,30146.0,N,Cash,N
9980,3500,3500,3500.0,36 months,11.39,115.24,B,B3,Financial Counselor,1 year,...,20.0,1.0,0.0,16123.0,6172.0,11000.0,0.0,N,Cash,N
9981,18800,18800,18800.0,36 months,17.86,678.35,D,D5,Chiropractor/President,5 years,...,0.0,1.0,0.0,425302.0,410698.0,9000.0,416302.0,N,Cash,N
9982,15950,15950,15950.0,60 months,30.49,520.85,F,F4,Accounts Payable Manager,6 years,...,100.0,5.0,0.0,38404.0,34078.0,8400.0,29004.0,N,Cash,N
9983,15000,15000,15000.0,36 months,14.99,519.91,C,C4,CSR,1 year,...,100.0,0.0,0.0,33575.0,23189.0,1200.0,29675.0,N,Cash,N
9984,8000,8000,8000.0,36 months,6.03,243.49,A,A1,Nurse,5 years,...,0.0,0.0,0.0,364699.0,56729.0,25400.0,78270.0,N,Cash,N
9985,12000,12000,12000.0,60 months,16.99,298.17,D,D3,Receptionist,6 years,...,75.0,0.0,0.0,34627.0,26070.0,5500.0,20127.0,N,Cash,N
9986,10000,10000,10000.0,60 months,17.97,253.78,D,D1,Costumer,5 years,...,0.0,0.0,0.0,23046.0,11065.0,10400.0,6346.0,N,Cash,N
9987,7500,7500,7500.0,36 months,7.49,233.27,A,A4,Revenue Analyst,< 1 year,...,66.7,0.0,0.0,51167.0,38664.0,34000.0,17167.0,N,Cash,N
9988,12500,12500,12500.0,36 months,11.67,413.22,B,B4,accounts payable,10+ years,...,28.6,0.0,0.0,144176.0,39356.0,14200.0,39844.0,N,Cash,N
9989,12000,12000,12000.0,60 months,11.49,263.86,B,B5,Engineer,10+ years,...,0.0,0.0,0.0,422666.0,81968.0,49100.0,74500.0,N,Cash,N
9990,35000,35000,35000.0,60 months,10.07,744.86,B,B2,Admistrative Assistant,7 years,...,60.0,0.0,0.0,91694.0,54079.0,22500.0,48094.0,N,Cash,N
9991,25000,25000,24950.0,36 months,11.49,824.29,B,B5,Senior contracts Manager,10+ years,...,80.0,0.0,0.0,297206.0,44313.0,10000.0,56106.0,N,Cash,N
9992,9600,9600,9600.0,36 months,13.35,325.09,C,C2,Welding,10+ years,...,100.0,0.0,0.0,56929.0,45424.0,5500.0,44684.0,N,Cash,N
9993,15000,15000,15000.0,60 months,16.91,372.07,C,C5,Systems Coordinator,4 years,...,66.7,0.0,0.0,78957.0,75609.0,19800.0,56257.0,N,DirectPay,N
9994,12000,12000,12000.0,36 months,10.99,392.81,B,B3,Quality Assurance (GS-11),10+ years,...,0.0,0.0,0.0,208866.0,7588.0,5400.0,4103.0,N,Cash,N
9995,28000,28000,28000.0,36 months,7.89,876.00,A,A5,parsonal assistan,9 years,...,44.4,0.0,0.0,791414.0,166387.0,110906.0,61542.0,N,Cash,Y
9996,15000,15000,15000.0,36 months,9.16,478.12,B,B2,NaN,NaN,...,12.5,0.0,0.0,62600.0,14406.0,40700.0,0.0,N,Cash,N
9997,5000,5000,5000.0,36 months,16.99,178.24,D,D1,NaN,NaN,...,10.0,0.0,1.0,31900.0,6465.0,29900.0,0.0,N,Cash,N
9998,11525,11525,11525.0,36 months,21.97,439.97,E,E4,warehouse recieving clerk,10+ years,...,33.3,0.0,0.0,102739.0,46545.0,5100.0,45758.0,N,Cash,N
9999,3000,3000,3000.0,36 months,18.49,109.20,D,D2,Intel,10+ years,...,100.0,0.0,0.0,470146.0,61338.0,11700.0,84946.0,N,Cash,N

In [11]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q6. Select Relevant Columns for Analysis 

The project manager of this project suggested looking into the following variables/columns for analysis, believing that they could be important in determining loan status: 

1. `loan_amnt`
2. `term` 
3. `int_rate`
4. `installment`
5. `grade`
6. `emp_length`
7. `home_ownership`
8. `annual_inc`
9. `verification_status`
10. `purpose`
11. `dti`
12. `delinq_2yrs`
13. `loan_status`

As such, filter down the previous DataFrame to just these columns, reducing from 86 columns to 14 columns. Name this new DataFrame as `loans_relevant_df`.  

**Expected Output**:

<img src="https://i.imgur.com/M99UOZE.png">

In [12]:
columns_to_select = ['loan_amnt','term','int_rate','installment','grade','emp_length','home_ownership','annual_inc','verification_status','purpose','dti','delinq_2yrs','loan_status']

loans_relevant_df = loans_significant_df[columns_to_select]

loans_relevant_df

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid

In [13]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

## Integer Encoding 

Most machine learning models handle numeric data better. Within the current dataset, you observe that there are categorical variables. There are two ways to transform non-numeric data to numeric data: <b>One-Hot Encoding</b> and <b>Integer Encoding</b>. For scalability (lesser columns), you've decided to conduct <b>integer encoding</b> to transform non-numerical data to numerical data, (0 to n).

The columns/variables to Integer Encode are:

1. `term`
2. `grade`
3. `emp_length`
4. `home_ownership`
5. `verification_status`
6.  `purpose`

The `loan_status` is omitted for now as it is your target variable. 

There are a total of 3 cells for each of the next 7 questions:

- Cell 1 - Inspect unique values
- Cell 2 - Create function
- Cell 3 - Apply function

### Q7. Create Integer Encoded Column For `term`

### Inspection 

Inspect the `term` column and create transform the unique values to integers.

There should be a total of <b>2</b> unique values: 

1. ' 36 months'
2. ' 60 months'

In [14]:
loans_relevant_df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

### Function or Map

With each unique value, encode them to integers between <b>0 to 1 </b>.

In [15]:
def int_encode_term(x):
    if(x == ' 36 months'):
        return 0
    else:
        return 1

### Apply 

Using the above function, `apply` it to the `term` column and create a new column called `term_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/6u3kb7k.png">

In [16]:
loans_relevant_df['term_int'] = loans_relevant_df['term'].apply(int_encode_term)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0

In [17]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q8. Create Integer Encoded Column For `grade`

### Inspection 

Inspect the `grade` column and create transform the unique values to integers.

There should be a total of <b>7</b> unique values.

In [18]:
loans_relevant_df['grade'].unique()

array(['E', 'A', 'B', 'C', 'D', 'F', 'G'], dtype=object)

### Function or Map

With each unique value, encode them to integers between <b>0 to 6 (inclusive)</b>.

In [19]:
def grade_encode(x):
    if (x == 'A'):
        return 0
    elif (x == 'B'):
        return 1
    elif (x == 'C'):
        return 2
    elif (x == 'D'):
        return 3
    elif (x == 'E'):
        return 4
    elif (x == 'F'):
        return 5
    elif (x == 'G'):
        return 6

### Apply 

Using the above function, `apply` it to the `grade` column and create a new column called `grade_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/yM0aZgN.png">

In [20]:
loans_relevant_df['grade_int'] = loans_relevant_df['grade'].apply(grade_encode)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3

In [21]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q9. Create Integer Encoded Column For `emp_length`

### Inspection 

Inspect the `emp_length` column and create transform the unique values to integers.

There should be a total of <b>12</b> unique values

In [22]:
loans_relevant_df['emp_length'].unique()

array(['< 1 year', '5 years', '1 year', '7 years', '9 years', '3 years',
       '10+ years', '4 years', '6 years', '8 years', '2 years', nan],
      dtype=object)

### Function or Map

With each unique value, encode them to integers between <b>-1 to 10 (inclusive)</b>, where -1 is for <b><code>NaN</code></b> values.

In [23]:
def emp_encode(x):
    if (x == '< 1 year'):
        return 0
    elif (x == '1 year'):
        return 1
    elif (x == '2 years'):
        return 2
    elif (x == '3 years'):
        return 3
    elif (x == '4 years'):
        return 4
    elif (x == '5 years'):
        return 5
    elif (x == '6 years'):
        return 6
    elif (x == '7 years'):
        return 7
    elif (x == '8 years'):
        return 8
    elif (x == '9 years'):
        return 9
    elif (x == '10+ years'):
        return 10
    else:
        return -1

### Apply 

Using the above function, `apply` it to the `emp_length` column and create a new column called `emp_length_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/sGzH2xg.png">

In [24]:
loans_relevant_df['emp_length_int'] = loans_relevant_df['emp_length'].apply(emp_encode)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int,emp_length_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4,0
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0,5
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1,1
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1,7
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2,7
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1,9
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2,3
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3,10
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1,10
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2,4
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1,10
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1,4
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4,0
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0,5
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2,10
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0,4
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1,6
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2,8
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0,2
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2,7
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1,-1
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1,3
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1,10
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1,10
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1,1
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3,8
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3,6
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3,6
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2,10
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2,10
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2,3
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0,10
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2,0
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3,3
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1,5
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0,3
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2,0
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2,1
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1,1
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3,5
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5,6
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2,1
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0,5
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3,6
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3,5
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0,0
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1,10
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1,10
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1,7
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1,10
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2,10
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2,4
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1,10
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0,9
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1,-1
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3,-1
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4,10
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3,10

In [25]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q10. Create Integer Encoded Column For `home_ownership`

### Inspection 

Inspect the `home_ownership` column and create transform the unique values to integers.

There should be a total of <b>6</b> unique values

In [26]:
loans_relevant_df['home_ownership'].unique()

array(['MORTGAGE', 'OWN', 'RENT', 'ANY', 'NONE', 'OTHER'], dtype=object)

### Function

With each unique value, encode them to integers between <b>0 to 5(inclusive)</b>.

In [27]:
def home_encode(x):
    if (x == 'MORTGAGE'):
        return 0
    elif (x == 'OWN'):
        return 1
    elif (x == 'RENT'):
        return 2
    elif (x == 'ANY'):
        return 3
    elif (x == 'NONE'):
        return 4
    elif (x == 'OTHER'):
        return 5

### Apply 

Using the above function, `apply` it to the `home_ownership` column and create a new column called `home_ownership_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/53IOzA3.png">

In [28]:
loans_relevant_df['home_ownership_int'] = loans_relevant_df['home_ownership'].apply(home_encode)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int,emp_length_int,home_ownership_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4,0,0
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0,5,1
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1,1,0
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1,7,0
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2,7,0
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1,9,2
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2,3,0
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3,10,0
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1,10,0
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2,4,0
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1,10,0
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1,4,2
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4,0,2
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0,5,2
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2,10,0
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0,4,0
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1,6,2
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2,8,0
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0,2,0
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2,7,2
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1,-1,0
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1,3,2
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1,10,2
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1,10,1
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1,1,0
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1,1,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3,8,2
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3,6,0
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3,6,0
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2,10,2
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2,10,1
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2,3,0
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0,10,0
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2,0,0
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3,3,0
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1,5,0
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0,3,2
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2,0,2
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2,1,2
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1,1,0
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3,5,0
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5,6,0
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2,1,2
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0,5,0
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3,6,2
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3,5,2
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0,0,2
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1,10,0
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1,10,0
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1,7,0
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1,10,0
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2,10,2
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2,4,2
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1,10,0
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0,9,0
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1,-1,2
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3,-1,0
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4,10,0
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3,10,0

In [29]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q11. Create Integer Encoded Column For `verification_status`

### Inspection 

Inspect the `verification_status` column and create transform the unique values to integers.

There should be a total of <b>3</b> unique values.

In [30]:
loans_relevant_df['verification_status'].unique()

array(['Verified', 'Source Verified', 'Not Verified'], dtype=object)

### Function or Map

With each unique value, encode them to integers between <b>0 to 2 (inclusive)</b>.

In [31]:
def verification_encode(x):
    if (x == 'Verified'):
        return 0
    elif (x == 'Source Verified'):
        return 1
    elif (x == 'Not Verified'):
        return 2

### Apply 

Using the above function, `apply` it to the `verification_status` column and create a new column called `verification_status_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/BPhTJ3M.png">

In [32]:
loans_relevant_df['verification_status_int'] = loans_relevant_df['verification_status'].apply(verification_encode)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int,emp_length_int,home_ownership_int,verification_status_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4,0,0,0
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0,5,1,1
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1,1,0,0
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1,7,0,1
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2,7,0,1
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1,9,2,1
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2,3,0,2
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3,10,0,1
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1,10,0,0
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2,4,0,0
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1,10,0,2
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1,4,2,2
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4,0,2,1
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0,5,2,1
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2,10,0,0
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0,4,0,0
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1,6,2,1
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2,8,0,1
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0,2,0,0
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2,7,2,0
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1,-1,0,1
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1,3,2,1
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1,10,2,1
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1,10,1,1
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1,1,0,1
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1,1,1,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3,8,2,1
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3,6,0,0
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3,6,0,1
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1,10,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2,10,2,2
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2,10,1,0
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2,3,0,1
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0,10,0,2
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2,0,0,2
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3,3,0,1
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1,5,0,2
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0,3,2,2
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2,0,2,1
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2,1,2,1
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1,1,0,1
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3,5,0,1
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5,6,0,1
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2,1,2,1
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0,5,0,2
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3,6,2,1
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3,5,2,1
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0,0,2,2
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1,10,0,1
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1,10,0,2
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1,7,0,2
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1,10,0,0
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2,10,2,1
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2,4,2,2
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1,10,0,0
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0,9,0,0
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1,-1,2,2
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3,-1,0,0
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4,10,0,0
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3,10,0,0

In [33]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q12. Create Integer Encoded Column For `purpose`

### Inspection 

Inspect the `purpose` column and create transform the unique values to integers.

There should be a total of <b>14</b> unique values

In [34]:
loans_relevant_df['purpose'].unique()

array(['other', 'debt_consolidation', 'home_improvement', 'credit_card',
       'car', 'small_business', 'medical', 'major_purchase', 'vacation',
       'house', 'moving', 'wedding', 'educational', 'renewable_energy'],
      dtype=object)

### Function or Map

With each unique value, encode them to integers between <b>0 to 13 (inclusive)</b>.

In [35]:
def purpose_encode(x):
    if (x == 'other'):
        return 0
    elif (x == 'debt_consolidation'):
        return 1
    elif (x == 'home_improvement'):
        return 2
    elif (x == 'credit_card'):
        return 3
    elif (x == 'car'):
        return 4
    elif (x == 'small_business'):
        return 5
    elif (x == 'medical'):
        return 6
    elif (x == 'major_purchase'):
        return 7
    elif (x == 'vacation'):
        return 8
    elif (x == 'house'):
        return 9
    elif (x == 'moving'):
        return 10
    elif (x == 'wedding'):
        return 11
    elif (x == 'educational'):
        return 12
    elif (x == 'renewable_energy'):
        return 13

### Apply 

Using the above function, `apply` it to the `purpose` column and create a new column called `purpose_int` to `loans_relevant_df`.

**Expected Output**:

<img src="https://i.imgur.com/89aRMEl.png">

In [36]:
loans_relevant_df['purpose_int'] = loans_relevant_df['purpose'].apply(purpose_encode)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int,emp_length_int,home_ownership_int,verification_status_int,purpose_int
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4,0,0,0,0
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0,5,1,1,1
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1,1,0,0,1
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1,7,0,1,2
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2,7,0,1,1
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1,9,2,1,1
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2,3,0,2,1
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3,10,0,1,1
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1,10,0,0,3
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2,4,0,0,1
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1,10,0,2,1
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1,4,2,2,1
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4,0,2,1,1
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0,5,2,1,1
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2,10,0,0,1
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0,4,0,0,2
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1,6,2,1,0
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2,8,0,1,1
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0,2,0,0,1
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2,7,2,0,1
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1,-1,0,1,1
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1,3,2,1,4
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1,10,2,1,1
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1,10,1,1,3
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1,1,0,1,1
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1,1,1,1,1
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3,8,2,1,3
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3,6,0,0,3
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3,6,0,1,1
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1,10,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2,10,2,2,1
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2,10,1,0,1
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2,3,0,1,3
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0,10,0,2,1
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2,0,0,2,4
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3,3,0,1,3
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1,5,0,2,3
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0,3,2,2,3
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2,0,2,1,3
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2,1,2,1,4
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1,1,0,1,1
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3,5,0,1,5
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5,6,0,1,1
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2,1,2,1,3
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0,5,0,2,1
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3,6,2,1,3
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3,5,2,1,1
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0,0,2,2,1
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1,10,0,1,1
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1,10,0,2,1
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1,7,0,2,1
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1,10,0,0,1
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2,10,2,1,1
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2,4,2,2,3
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1,10,0,0,2
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0,9,0,0,3
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1,-1,2,2,1
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3,-1,0,0,1
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4,10,0,0,1
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3,10,0,0,0

In [37]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q13. Create New `income_tax` column

An **income tax** is imposed on the annual income of all registerants. The tax is calculated as follows:

- if the annual income is $\$65,000$ or less, the registrant does not need to pay tax
- if the  annual income is more than $\$65,000$ the registrant needs to pay a tax equal to $7.5\%$ of his/her annual income

Mathematically, for an registrant with an income of $\$annual\_income$, the amount of tax the registrant needs to pay, or the $\$tax$ is:

$$
tax = \begin{cases}
0 & \text{ if } annual\_income \leq 65000\\
0.075 \times annual\_income & \text{ if } annual\_income > 65000\\\end{cases}
$$

You've been tasked to create a new column called `income_tax` based on the above conditions.

In [38]:
def calculate_income_tax(x):
    if (x <= 65000):
        return 0
    else:
        return x * 7.5 / 100

**Expected Output**:

<img src="https://i.imgur.com/u54cP8a.png">

In [39]:
loans_relevant_df['income_tax'] = loans_relevant_df['annual_inc'].apply(calculate_income_tax)
loans_relevant_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,loan_status,term_int,grade_int,emp_length_int,home_ownership_int,verification_status_int,purpose_int,income_tax
0,1800,36 months,19.52,66.46,E,< 1 year,MORTGAGE,130000.0,Verified,other,15.49,0.0,Fully Paid,0,4,0,0,0,0,9750.000
1,6800,36 months,7.97,213.00,A,5 years,OWN,102960.0,Source Verified,debt_consolidation,10.54,2.0,Fully Paid,0,0,5,1,1,1,7722.000
2,18000,36 months,12.49,602.08,B,1 year,MORTGAGE,60000.0,Verified,debt_consolidation,27.06,0.0,Fully Paid,0,1,1,0,0,1,0.000
3,17375,36 months,13.11,586.36,B,7 years,MORTGAGE,49000.0,Source Verified,home_improvement,11.76,0.0,Charged Off,0,1,7,0,1,2,0.000
4,14000,60 months,13.59,322.79,C,7 years,MORTGAGE,45000.0,Source Verified,debt_consolidation,14.32,0.0,Current,1,2,7,0,1,1,0.000
5,35000,60 months,12.73,791.53,B,9 years,RENT,125000.0,Source Verified,debt_consolidation,31.85,0.0,Current,1,1,9,2,1,1,9375.000
6,8000,36 months,12.74,268.56,C,3 years,MORTGAGE,35000.0,Not Verified,debt_consolidation,14.99,0.0,Fully Paid,0,2,3,0,2,1,0.000
7,35000,60 months,17.57,880.61,D,10+ years,MORTGAGE,170000.0,Source Verified,debt_consolidation,8.43,3.0,Fully Paid,1,3,10,0,1,1,12750.000
8,3000,36 months,11.49,98.92,B,10+ years,MORTGAGE,30000.0,Verified,credit_card,28.92,2.0,Fully Paid,0,1,10,0,0,3,0.000
9,6000,36 months,14.03,205.16,C,4 years,MORTGAGE,48000.0,Verified,debt_consolidation,19.92,1.0,Fully Paid,0,2,4,0,0,1,0.000
10,3025,36 months,9.58,97.02,B,10+ years,MORTGAGE,85000.0,Not Verified,debt_consolidation,12.09,0.0,Current,0,1,10,0,2,1,6375.000
11,12875,36 months,13.67,437.98,B,4 years,RENT,65000.0,Not Verified,debt_consolidation,11.48,0.0,Fully Paid,0,1,4,2,2,1,0.000
12,10800,60 months,18.55,277.50,E,< 1 year,RENT,60000.0,Source Verified,debt_consolidation,14.04,0.0,Fully Paid,1,4,0,2,1,1,0.000
13,7000,36 months,7.89,219.00,A,5 years,RENT,33000.0,Source Verified,debt_consolidation,16.71,0.0,Current,0,0,5,2,1,1,0.000
14,10000,36 months,12.62,335.12,C,10+ years,MORTGAGE,60000.0,Verified,debt_consolidation,27.69,0.0,Current,0,2,10,0,0,1,0.000
15,30000,36 months,6.99,926.18,A,4 years,MORTGAGE,150000.0,Verified,home_improvement,0.20,0.0,Fully Paid,0,0,4,0,0,2,11250.000
16,24000,60 months,9.93,509.11,B,6 years,RENT,121620.0,Source Verified,other,1.30,0.0,Current,1,1,6,2,1,0,9121.500
17,16000,60 months,14.33,375.04,C,8 years,MORTGAGE,88541.0,Source Verified,debt_consolidation,14.64,0.0,Fully Paid,1,2,8,0,1,1,6640.575
18,16000,36 months,6.97,493.82,A,2 years,MORTGAGE,180000.0,Verified,debt_consolidation,14.66,0.0,Fully Paid,0,0,2,0,0,1,13500.000
19,16000,60 months,14.46,376.12,C,7 years,RENT,57900.0,Verified,debt_consolidation,20.64,0.0,Current,1,2,7,2,0,1,0.000
20,19200,60 months,8.18,390.97,B,NaN,MORTGAGE,85884.0,Source Verified,debt_consolidation,21.15,0.0,Fully Paid,1,1,-1,0,1,1,6441.300
21,4000,36 months,12.12,133.09,B,3 years,RENT,42000.0,Source Verified,car,7.97,0.0,Fully Paid,0,1,3,2,1,4,0.000
22,10000,36 months,10.90,326.92,B,10+ years,RENT,40000.0,Source Verified,debt_consolidation,25.35,0.0,Current,0,1,10,2,1,1,0.000
23,17350,36 months,10.99,567.94,B,10+ years,OWN,51900.0,Source Verified,credit_card,12.37,0.0,Current,0,1,10,1,1,3,0.000
24,1200,36 months,11.49,39.57,B,1 year,MORTGAGE,75000.0,Source Verified,debt_consolidation,14.21,0.0,Fully Paid,0,1,1,0,1,1,5625.000
25,20000,60 months,9.75,422.49,B,1 year,OWN,85200.0,Source Verified,debt_consolidation,8.03,0.0,Fully Paid,1,1,1,1,1,1,6390.000
26,12000,36 months,18.94,439.51,D,8 years,RENT,48000.0,Source Verified,credit_card,14.30,0.0,Current,0,3,8,2,1,3,0.000
27,30000,60 months,18.06,762.79,D,6 years,MORTGAGE,59610.0,Verified,credit_card,22.94,0.0,Current,1,3,6,0,0,3,0.000
28,30000,60 months,20.20,798.16,D,6 years,MORTGAGE,92000.0,Source Verified,debt_consolidation,12.21,0.0,Fully Paid,1,3,6,0,1,1,6900.000
29,3000,36 months,10.08,96.92,B,10+ years,MORTGAGE,48000.0,Not Verified,home_improvement,14.93,0.0,Current,0,1,10,0,2,2,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,12000,36 months,12.62,402.14,C,10+ years,RENT,45000.0,Not Verified,debt_consolidation,34.72,0.0,Current,0,2,10,2,2,1,0.000
9971,8000,36 months,16.02,281.34,C,10+ years,OWN,41000.0,Verified,debt_consolidation,8.02,0.0,Charged Off,0,2,10,1,0,1,0.000
9972,10000,36 months,15.05,346.90,C,3 years,MORTGAGE,49500.0,Source Verified,credit_card,29.67,0.0,Current,0,2,3,0,1,3,0.000
9973,20000,36 months,7.89,625.72,A,10+ years,MORTGAGE,56000.0,Not Verified,debt_consolidation,22.64,0.0,Fully Paid,0,0,10,0,2,1,0.000
9974,6000,36 months,14.49,206.50,C,< 1 year,MORTGAGE,35000.0,Not Verified,car,9.67,0.0,Fully Paid,0,2,0,0,2,4,0.000
9975,17500,60 months,16.99,434.83,D,3 years,MORTGAGE,35000.0,Source Verified,credit_card,13.66,0.0,Charged Off,1,3,3,0,1,3,0.000
9976,18000,36 months,10.99,589.22,B,5 years,MORTGAGE,95000.0,Not Verified,credit_card,16.61,0.0,Fully Paid,0,1,5,0,2,3,7125.000
9977,10000,36 months,8.46,315.50,A,3 years,RENT,60000.0,Not Verified,credit_card,3.42,0.0,Current,0,0,3,2,2,3,0.000
9978,22250,36 months,13.99,760.35,C,< 1 year,RENT,58000.0,Source Verified,credit_card,25.43,0.0,Fully Paid,0,2,0,2,1,3,0.000
9979,7000,36 months,15.02,242.73,C,1 year,RENT,193000.0,Source Verified,car,6.81,0.0,Current,0,2,1,2,1,4,14475.000
9980,3500,36 months,11.39,115.24,B,1 year,MORTGAGE,45000.0,Source Verified,debt_consolidation,7.92,0.0,Fully Paid,0,1,1,0,1,1,0.000
9981,18800,36 months,17.86,678.35,D,5 years,MORTGAGE,50000.0,Source Verified,small_business,11.59,0.0,Fully Paid,0,3,5,0,1,5,0.000
9982,15950,60 months,30.49,520.85,F,6 years,MORTGAGE,42000.0,Source Verified,debt_consolidation,25.46,0.0,Current,1,5,6,0,1,1,0.000
9983,15000,36 months,14.99,519.91,C,1 year,RENT,8000.0,Source Verified,credit_card,85.74,0.0,Current,0,2,1,2,1,3,0.000
9984,8000,36 months,6.03,243.49,A,5 years,MORTGAGE,120000.0,Not Verified,debt_consolidation,17.45,0.0,Fully Paid,0,0,5,0,2,1,9000.000
9985,12000,60 months,16.99,298.17,D,6 years,RENT,48000.0,Source Verified,credit_card,5.73,0.0,Fully Paid,1,3,6,2,1,3,0.000
9986,10000,60 months,17.97,253.78,D,5 years,RENT,30000.0,Source Verified,debt_consolidation,13.04,0.0,Current,1,3,5,2,1,1,0.000
9987,7500,36 months,7.49,233.27,A,< 1 year,RENT,55000.0,Not Verified,debt_consolidation,17.54,0.0,Fully Paid,0,0,0,2,2,1,0.000
9988,12500,36 months,11.67,413.22,B,10+ years,MORTGAGE,44000.0,Source Verified,debt_consolidation,30.41,1.0,Fully Paid,0,1,10,0,1,1,0.000
9989,12000,60 months,11.49,263.86,B,10+ years,MORTGAGE,108000.0,Not Verified,debt_consolidation,31.12,0.0,Current,1,1,10,0,2,1,8100.000
9990,35000,60 months,10.07,744.86,B,7 years,MORTGAGE,80000.0,Not Verified,debt_consolidation,21.27,0.0,Current,1,1,7,0,2,1,6000.000
9991,25000,36 months,11.49,824.29,B,10+ years,MORTGAGE,65000.0,Verified,debt_consolidation,26.42,0.0,Current,0,1,10,0,0,1,0.000
9992,9600,36 months,13.35,325.09,C,10+ years,RENT,38000.0,Source Verified,debt_consolidation,33.39,0.0,Fully Paid,0,2,10,2,1,1,0.000
9993,15000,60 months,16.91,372.07,C,4 years,RENT,63000.0,Not Verified,credit_card,17.94,0.0,Current,1,2,4,2,2,3,0.000
9994,12000,36 months,10.99,392.81,B,10+ years,MORTGAGE,68000.0,Verified,home_improvement,3.78,0.0,Fully Paid,0,1,10,0,0,2,5100.000
9995,28000,36 months,7.89,876.00,A,9 years,MORTGAGE,400000.0,Verified,credit_card,13.38,0.0,Charged Off,0,0,9,0,0,3,30000.000
9996,15000,36 months,9.16,478.12,B,NaN,RENT,50000.0,Not Verified,debt_consolidation,7.71,0.0,Fully Paid,0,1,-1,2,2,1,0.000
9997,5000,36 months,16.99,178.24,D,NaN,MORTGAGE,60000.0,Verified,debt_consolidation,4.14,0.0,Current,0,3,-1,0,0,1,0.000
9998,11525,36 months,21.97,439.97,E,10+ years,MORTGAGE,50000.0,Verified,debt_consolidation,27.44,0.0,Charged Off,0,4,10,0,0,1,0.000
9999,3000,36 months,18.49,109.20,D,10+ years,MORTGAGE,200000.0,Verified,other,15.14,0.0,Fully Paid,0,3,10,0,0,0,15000.000

In [40]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q14. Save Transformed Data as CSV

Save the transformed dataset, with both the numeric (integer encoded) and non-numerical data as a new CSV file as `loans_transformed.csv`.

In [41]:
loans_relevant_df.to_csv('loans_transformed.csv', index=False)

In [42]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q15. Save Numeric Only Data as CSV
Save the transformed dataset with only the numeric variables as a new CSV file as `loans_transformed_numeric.csv`.

In [43]:
columns_to_select = ['term_int', 'grade_int', 'emp_length_int', 'home_ownership_int', 'verification_status_int', 'purpose_int']
loans_transformed_df = loans_relevant_df[columns_to_select]
loans_transformed_df.to_csv('loans_transformed_numeric.csv', index=False)

In [44]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 0.5/1

#do not hardcode the columns names, instead you can use the select_dtypes function
#floats are considered as numeric values

## Exploratory & Statistical Analysis - 5 marks

After performing data wrangling and preprocessing on the given datasets, you are now tasked to perform some descriptive analysis based on your processed dataset in order to better understand the dataset you're working with.

### Q16. Summary Statistics for Loan Amount for each Grade

You're interested in finding out what is the distribution of the loan amounts issued by each grade. `groupby` the `loans_relevant_df` by its `grade` and `describe()` based on the `loan_amnt`.

In [56]:
grade_gb = loans_relevant_df.groupby('grade')
grade_gb['loan_amnt'].describe()

,count,mean,std,min,25%,50%,75%,max
grade,,,,,,,,
A,3800.0,14436.697368,9069.023093,1000.0,7662.50,12000.0,20000.00,40000.0
B,5900.0,14045.360169,8935.579266,1000.0,7200.00,12000.0,20000.00,40000.0
C,5688.0,15002.426160,9274.019663,1000.0,8000.00,13000.0,20000.00,40000.0
D,2901.0,15774.069286,9156.755279,1000.0,9000.00,14500.0,21175.00,40000.0
E,1230.0,17179.146341,9381.335781,1000.0,10000.00,16000.0,24000.00,40000.0
F,369.0,19750.677507,9820.715521,1000.0,12000.00,19725.0,28000.00,40000.0
G,112.0,20971.428571,8650.197140,2450.0,14631.25,20000.0,29231.25,40000.0

In [57]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q17. Summary Statistics for Purpose for each Grade

ou're interested in finding out what is the distribution of the loan amounts issued by each grade. `groupby` the `loans_relevant_df` by its `grade` and `describe()` based on the `purpose`.

In [47]:
grade_gb = loans_relevant_df.groupby('grade')
grade_gb['purpose'].describe()

      count unique                 top  freq
grade
A      3800     13  debt_consolidation  1815
B      5900     14  debt_consolidation  3205
C      5688     13  debt_consolidation  3382
D      2901     13  debt_consolidation  1814
E      1230     13  debt_consolidation   788
F       369     12  debt_consolidation   246
G       112     10  debt_consolidation    72

In [48]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q18.  `Charged Off` Proportion

In order to better understand the scale of the default by grade, you decide to get the proportion of loans that are charged off based on each grade. This would allow you to narrow to a grade which could be an issue. 

`groupby` the `grade` and get the `size` of each grade and store it in a variable. On a separate second variable, filter the column `loan_status` for only `Charged Off` and then `groupby` `grade` from the filtered data and get the `size` of each grade. With these two variables, get the percentage by having the first variable divided by the second variable.

<i>Note: Charged Off is the same as defaulting on a loan</i>

**Expected Output**:

    grade
    A    0.035526
    B    0.078644
    C    0.129395
    D    0.193382
    E    0.284553
    F    0.308943
    G    0.357143
    dtype: float64

In [49]:
grade_gb = loans_relevant_df.groupby('grade')
size_of_grade = grade_gb.size()
cond1 = (loans_relevant_df['loan_status'] == 'Charged Off')
filtered_df = loans_relevant_df[cond1]
filtered_grade_gb = filtered_df.groupby('grade')
size_of_filtered_grade = filtered_grade_gb.size()
size_of_grade =  size_of_filtered_grade / size_of_grade
size_of_grade

grade
A    0.035526
B    0.078644
C    0.129395
D    0.193382
E    0.284553
F    0.308943
G    0.357143
dtype: float64

In [50]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q19. Grade G Analysis -  Debt Consolidation

Based on the earlier analysis, you've seen that Grade `G` has the highest proportion of defaulters. As such you decided to investigate further by looking at the proportion of debt consolidation for Grade `G`. 

Create 3 filter conditions:

1. `loan_status` is `Charged Off`
2. `grade` is `G`
3. `purpose` is `debt_consolidation`

Create two Grade `G` DataFrame of `debt_consolidation`, where one has `charged_off`, one does not then get the proportion of charged off over the total. 

**Expected Output**:

    0.4027777777777778

In [51]:
cond1 = (loans_relevant_df['loan_status'] == 'Charged Off')
cond2 = (loans_relevant_df['grade'] == 'G')
cond3 = (loans_relevant_df['purpose'] == 'debt_consolidation')

df1 = loans_relevant_df[cond1 & cond2 & cond3]
df2 = loans_relevant_df[~cond1 & cond2 & cond3]

proportion_charged_off = len(df1) / (len(df1) + len(df2))
proportion_charged_off

0.4027777777777778

In [52]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Q20. Outlier Analysis

Your project manager wants to investigate if the large proportions of the outliers based on `annual_inc` are `Charged Off`. 

First get the 25th and 75th percentile, then filter for these outliers (without filtering for `Charged Off`, i.e entire dataset) based on the interquartile range. 

Extract these outliers and filter them for the `loan_status` of `Charged Off` and get the proportion of these outliers with and without `Charged Off`.

**Expected Output**:

    0.08832807570977919

In [53]:
quartile_1 = loans_relevant_df['annual_inc'].quantile(q=0.25)
quartile_3 = loans_relevant_df['annual_inc'].quantile(q=0.75)

IQR = quartile_3 - quartile_1

lower_bound = quartile_1 - 1.5 * IQR
upper_bound = quartile_3 + 1.5 * IQR


outlier_condition = ~loans_relevant_df['annual_inc'].between(lower_bound, upper_bound)
outliers_df = loans_relevant_df[outlier_condition]

cond1 = outliers_df['loan_status'] == 'Charged Off'

df1 = outliers_df[cond1]

proportion = len(df1) / len(outliers_df)
proportion

0.08832807570977919

In [54]:
## TA/INSTRUCTOR ONLY
## MARKS AWARDED: 1/1

### Optional - Analysis Comments (No marks but possibly insightful)

Add any additional comments/insights about this problem sets and our teaching team could reply to it.

<div class="alert alert-success">
<b>Checkpoint</b>: When you have completed, upload your progress to eLearn. eLearn only accepts the latest notebooks so if you have an existing notebook, your latest upload will <b>override</b> it.
</div>